#!/bin/sh
commit_msg_file=$1
if [ -f "$commit_msg_file" ]; then
    commit_msg=$(cat "$commit_msg_file")
else
    commit_msg=$(git log -1 --pretty=%B 2>/dev/null)
fi

if [ -n "$commit_msg" ]; then
    if ! echo "$commit_msg" | grep -qE "^TASK-[0-9]+: "; then
        echo "Error: Commit message must start with 'TASK-123: Format'!"
        exit 1
    fi
fi
exit 0
